### ISSUE TITLE
Missing file for VideoSubFinder Files

### ISSUE THREAD

**Issue by hush2nino** [BAAI-Agents/Cradle#14]
Thank you for your work. I encountered an issue while trying to run the code according to the readme documentation. My VideoSubFinder was missing a test.srt file after downloading and overwriting general.clg, which caused the code to not run.

**Comment by DVampire** [comment]
We are sorry for the confusion, the file test.srt is not necessary. You can create an empty test.srt file under res/tool/subfinder to run it. We encourage you to explore Cradle and welcome any further questions or feedback you may have.

**Comment by tellarin** [comment]
We have added a placeholder srt file in the repo and updated the setup instructions to avoid this issue.

Thanks again for your feedback, @hush2nino.
