### ISSUE TITLE
cannot import name '_pyautogui_win' from partially initialized module 'pyautogui'

### ISSUE THREAD

**Issue by ZhaojunCP** [BAAI-Agents/Cradle#17]
Hello! Thanks for your awesome work!
I got a problem when running the script` prototype_runner.py` . I completely follow your instructions on README.md and I don't know the reasons. The details are as follws:
![image](https://github.com/BAAI-Agents/Cradle/assets/167271971/27017b2b-b911-410e-b5b9-8300ed4563d9)
Looking forward to your reply!

**Comment by DVampire** [comment]
It seems that pyautogui hasn't been installed successfully. It's possible that your previous installation attempt might have caused some issues. Could you please try reinstalling pyautogui with version 0.9.54 using `pip install pyautogui==0.9.54` to match our compatible version? Thank you very much for your attention to our work. If you encounter any issues, please feel free to contact us.

**Comment by ZhaojunCP** [comment]
> It seems that pyautogui hasn't been installed successfully. It's possible that your previous installation attempt might have caused some issues. Could you please try reinstalling pyautogui with version 0.9.54 using `pip install --force-reinstall pyautogui==0.9.54` to match our compatible version? Thank you very much for your attention to our work. If you encounter any issues, please feel free to contact us.

Thanks for your reply! I have solved the problem by turning the version of python to 3.9. In python 3.10, the problem still exists.
