### ISSUE TITLE
ERROR: No matching distribution found for win32process

### ISSUE THREAD

**Issue by GenerallRoss** [BAAI-Agents/Cradle#49]
After creating and activating a new virtual environment `conda-dev `and attempting to install dependencies using the command `pip3 install -r requirements.txt`, the following error occurs:
ERROR: Could not find a version that satisfies the requirement win32process (from versions: none)
ERROR: No matching distribution found for win32process

**Comment by GenerallRoss** [comment]
Update: current branch is `dev-software`

**Comment by WeihaoTan** [comment]
Hi. We have merged both dev-software and dev-games into the main branch and these two branches are deprecated now. Could you follow the readme in the main branch to install the libraries and see whether the issue still exists? Thanks.

**Comment by GenerallRoss** [comment]
Yes, thank you, it's wprked!
