### ISSUE TITLE
cannot import name '_pyautogui_win' from partially initialized module 'pyautogui'

### ISSUE THREAD

**Issue by GenerallRoss** [BAAI-Agents/Cradle#50]
On the first run, the following error occurs:
![изображение](https://github.com/BAAI-Agents/Cradle/assets/105162895/baecfa22-3723-4fa2-8a18-58915b759e03)
I have already seen the same issue, tried running the command `pip install --force-reinstall pyautogui==0.9.54`, but the error is still present. Python version 3.10.14

**Comment by DVampire** [comment]
You can try to turn the version of python to 3.9 follow the `https://github.com/BAAI-Agents/Cradle/issues/17`. If there are still problems, please feel free to contact us.
