### ISSUE TITLE
如何添加自定义软件，自定义动作？

### ISSUE THREAD

**Issue by bobiscool** [BAAI-Agents/Cradle#66]
如题，比如自己想用ai操作某个自定义的程序

**Comment by XinrunXu** [comment]
Look at the readme here～
[how-to-implement-cradle-on-other-software](https://github.com/BAAI-Agents/Cradle/blob/main/docs/envs/software.md#how-to-implement-cradle-on-other-software)

**Comment by WeihaoTan** [comment]
You can also take a look at the File Structure in the readme, which tells you the files you can modify to customize your agent.
And this post provides an overall  perspective of how to adapt the framework to a new game: `https://github.com/BAAI-Agents/Cradle/discussions/55`
