### ISSUE TITLE
都是华人团队 为什么会没有中文文档？

### ISSUE THREAD

**Issue by good1uck** [BAAI-Agents/Cradle#67]

**Comment by DVampire** [comment]
Thank you for your feedback. While our team includes both Chinese and international members, we strive to reach a global audience, and English documentation helps us achieve that. However, we understand the importance of providing resources in multiple languages and are working on expanding our documentation to include Chinese in the future. We appreciate your understanding and patience.

**Comment by good1uck** [comment]
ⵜⴰⵏⴻⵎⵎⵉⵔⵜ ⵖⴻⴼ ⵜⵎⵓⵖⵍⵉⵉⵏⴻⴽ. ⵎⴰ ⵢⴻⵍⵍⴰ ⴷⴻⴳ ⵜⴻⵔⴱⴰⵄⵜⵏⵏⴻⵖ ⵜⴻⵙⵄⴰ ⴰⵎⴰ ⴷ ⵉⵄⴻⴳⴳⴰⵍⴻⵏ ⵉⵛⵉⵏⵡⴰⵜⴻⵏ, ⴰⵎⴰ ⴷ ⵉⵄⴻⴳⴳⴰⵍⴻⵏ ⵉⴳⵔⴰⵖⵍⴰⵏⴻⵏ, ⵏⴻⵄⵔⴻⴹ ⴰⴷ ⵏⴰⵡⴻⴹ ⵖⴻⵔ ⵢⵉⵡⴻⵏ ⵏ ⵡⴻⴳⴷⵓⴷ ⴰⵎⴰⴹⵍⴰⵏ, ⵢⴻⵔⵏⴰ ⵜⵜⴰⵡⵉⵍⴰⵜ ⵏ ⵜⴻⴳⵍⵉⵣⵉⵜ ⵜⵜⵄⴰⵡⴰⵏⴻⵏⴰⵖ ⴰⴷ ⵏⴰⵡⴻⴹ ⵖⴻⵔ ⵡⴰⵢⴰ. ⴷ ⴰⵛⵓ ⴽⴰⵏ, ⵏⴻⴼⵀⴻⵎ ⴰⵣⴰⵍ ⵏ ⵓⵙⵙⵉⵡⴻⴹ ⵏ ⵜⵜⴰⵡⵉⵍⴰⵜ ⵙ ⵡⴰⵟⴰⵙ ⵏ ⵜⵓⵜⵍⴰⵢⵉⵏ ⵢⴻⵔⵏⵓ ⵍⴰ ⵏⴻⵅⴷⴻⵎ ⴰⴽⴽⴻⵏ ⴰⴷ ⵏⴻⵙⵙⴻⵎⵖⴻⵔ ⵉⴹⵔⵉⵙⴻⵏⵏⵏⴻⵖ (documents) ⴰⴽⴽⴻⵏ ⴰⴷ ⴷⵏⴻⵙⵙⴻⴽⵛⴻⵎ ⵜⴰⵛⵉⵏⵡⴰⵜ ⵖⴻⵔ ⵙⴷⴰⵜ. ⵏⴻⵜⵜⵇⴰⴷⴰⵔ ⵜⵉⴼⵔⴰⵜⵉⴽ ⴷ ⵚⵚⴱⴻⵔⵉⴽ.
