### ISSUE TITLE
在M系列的MacBook上可以用么

### ISSUE THREAD

**Issue by learningpro** [BAAI-Agents/Cradle#68]
如题，可以在M系列的Mac上使用么

**Comment by DVampire** [comment]
As mentioned in issue https://github.com/BAAI-Agents/Cradle/issues/58, our Cradle framework is not limited by the system; it is only constrained by whether the game can run on the corresponding operating system. For example, RDR2 and Dealers Life 2 can only run on Windows, while Stardew and Skylines can run on both Windows and Mac. Therefore, both Stardew and Skylines can be used on Macs with M series chips.
