### ISSUE TITLE
星露谷中，为什么主角能够直接且准确地找到去购物商店的路（任务是去商店购买东西）？

### ISSUE THREAD

**Issue by duoyw** [BAAI-Agents/Cradle#71]

**Comment by WeihaoTan** [comment]
We provide a hint like "the store is on the right side of the house" in the prompt as minimal guidance.  And there is a board that says 'Pierre's' in front of the store, indicating Pierre's General Store.

**Comment by duoyw** [comment]
8. If you want to purchase items, then you should move up to stand in front of the shopkeeper's counter, move sligntly to align with the green counter and buy items. After purchasing, you can move down to the exit and leave store.
9. If you want to leave town, you should move along gray cobblestone road to the left of the store and the clinic.

However, this guide is too clear and amounts to a step-by-step guide to what the larger model does.

**Comment by WeihaoTan** [comment]
As mentioned in the paper, this task is very challenging and even if we provide detailed guidance, the success rate is quite low. We also desire to know the better prompt and approach for accomplishing this task efficiently. And we would be glad to hear if you had a better solution.
