### ISSUE TITLE
Why do we need to provide subtasks?

### ISSUE THREAD

**Issue by duoyw** [BAAI-Agents/Cradle#74]
{
    "id": 1,
    "task_description": "Search for an article with title containing \"Towards General Computer Control\" and save its PDF file.",
    "sub_task_description_list": [
        "Search for \"Towards General Computer Control\"",
        "Go to the PDF page of an article starting with \"Towards General Computer Control\"",
        "Save the PDF file"
    ]
}

I noticed that in the document "env_config_chrome.json", it is necessary to explicitly provide the sub_task_description_list in the description of each task. Why is this?

**Comment by WeihaoTan** [comment]
Sorry for the confusion. The subtask is actually each step of the task, which is useful for step-level debugging. They are not necessary for completing the task. And they will be deprecated in the incoming update.
