### ISSUE TITLE
循环依赖问题

### ISSUE THREAD

**Issue by 627539904** [BAAI-Agents/Cradle#87]
cardle.confg.config.py循环依赖cardle.gameio.gui_utils.py。
cardle.gameio.gui_utils.py与cardle.gameio.io_env.py循环依赖。
Config类，TargetWindow类，IOEnvironment类之间绕成一团。
这是我目前刚开始尝试运行项目就遇到的问题。
是我太菜了吗？
还是说，python中存在一种不需要在乎循环依赖就能正常运行的方式？
但看很多人提的问题都是已经能使用的问题。
是循环依赖不是问题，还是说他们都重构了一遍？
如果是项目本来就可以正常运行，请教一下，如何在保持大量循环依赖的情况下运行项目？
ps:
如果可以，我不想大面积重构项目，这样后面版本更新就没法用了。

**Comment by WeihaoTan** [comment]
Thanks for reaching out. Could you elaborate on which env you are running? The code worked on our side and many other users also ran it successfully.

**Comment by 627539904** [comment]
Win11,VsCode,Pip

对于config.py和gameio模块的循环依赖，目前我是通过将config.py的import cradle.gameio从全局导入替换为局部导入临时解决的。但原有代码确实没办法直接运行，一直提示循环依赖。
和其他难以快速定位的问题不同，因为这是代码的结构的问题，过于明显，所以我很困惑。我甚至一度以为，Python已经能够智能解决循环依赖问题，或者您以及其他用户安装了能自动解决循环依赖的环境。但我并没有找到如此智能的方案。
从您的答复来看，循环依赖问题不是明确被解决了，而是没出现，或其他遇到的人没有提出。

所以，附上临时解决方式，或许对其他人有用：
![cradle_循环依赖_01](https://github.com/user-attachments/assets/62646317-d217-4187-b5c5-8b0b063fcafa)
![cradle_循环依赖_02](https://github.com/user-attachments/assets/d0250e4b-44b8-4812-b9f0-e83551e11bc9)

这不是一个优雅的解决方案，但可以临时凑合用。
随着项目复杂度的提升，后续可能有更好的解耦方式。

**Comment by Aues6uen11Z** [comment]
我pyautogui降级到0.9.51可以，https://github.com/asweigart/pyautogui/issues/525

**Comment by 627539904** [comment]
除了循环依赖，我还遇到了多屏情况下，分辨率难以准确获取的问题。
比如，对于Chrome，单屏情况下只有一个活动窗口，多屏情况下会读取到两个活动窗口。程序似乎是随机读取一个窗口，但继续向下后，分辨率会变成很奇怪的256*168这样的非常小的数字。
我放弃了，目前该项目似乎不太适合我直接使用，我期望的通用控制是基于自然视觉。但目前项目的是基于应用，存在交互边界，对于个人的实际使用场景暂时用不上。

**Comment by Aues6uen11Z** [comment]
我单屏也是分辨率不准，需要运行程序后手动把窗口点到前台才行
